nginx:
  build: ./nginx
  volumes: 
   - ./client/dist:/usr/share/nginx/html
  ports:
   - "80:80"
  links:
   - jboss
jboss:
  build: ./jboss
  volumes:
   - .:/home/opendata/app
  links:
   - db
  ports:
   - "8081:8080"
   - "9999:9999"
   - "9990:9990"
  command: /home/opendata/deploy.sh
dbdata:
  image: postgres:9.3
  volumes:
    - /var/lib/postgresql
  command: "true"
db:
  build: ./postgres
  volumes_from:
    - dbdata
  ports:
   - "5434:5432"
